name: Docs
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]
jobs:
  update-docs:
    name: Update docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1

      - name: Install V
        uses: nocturlab/setup-vlang-action@v1
        with:
          v-version: master

      - name: Generate documentation
        run: |
          mkdir -p docs
          v doc -f html -inline-assets -no-timestamp -all -o docs .
          rm -f $DOCS_DIR/index.html
          mv docs/*.html docs/index.html

      - name: Update documentation
        uses: test-room-7/action-update-file@v1
        with:
          file-path: docs/*
          commit-msg: Update documentation
          github-token: ${{ secrets.GITHUB_TOKEN }}
